[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SUPABASE_URL = "https://rguvsbtqbvvcevwwwwpj.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJndXZzYnRxYnZ2Y2V2d3d3d3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTgxNzgsImV4cCI6MjA2OTg5NDE3OH0.Yf3AWl664p14V1IjhdgUwHgIPAPPv95PPGFBhcDw7nI"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJndXZzYnRxYnZ2Y2V2d3d3d3BqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDMxODE3OCwiZXhwIjoyMDY5ODk0MTc4fQ.7PQYcyxMPAe7oY7c5ycveM0xbSoJYjIAyOCQeOmnCbc"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
